### PR TITLE
fix: Update minimal required vscode version to 1.49.0

### PR DESCRIPTION
**Pull request by dvandra**
Jira Issue: https://issues.redhat.com/browse/APPAI-1680

### CODE REVIEW

**Comment by dvandra** [comment]
[test]

**Review by arajkumar — APPROVED** [review]
lgtm

**Comment by arajkumar** [comment]
@dvandra you may need to update test runTests.ts as well.

**Review by mathur07 — APPROVED** [review]
lgtm

**Review by jparsai — APPROVED** [review]

**Pull request merged**
