### PR TITLE
chore: Update to latest fabric8-analytics-lsp-server to 0.2.1

### PR DESCRIPTION
**Pull request by mathur07**
- https://www.npmjs.com/package/fabric8-analytics-lsp-server

### CODE REVIEW

**Comment by dvandra** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by arajkumar** [comment]
@mathur07 You need to update package-lock.json as well. Do the following steps,

1. Update lsp version in package.json
2. Run `npm install` (it will update package-lock.json)
3. Add both package.json & package-lock.json for review

**Comment by dvandra** [comment]
Screenshot from 2020-06-25 12-50-34

**Pull request merged**
