### PR TITLE
feat: Add shortcut icon for Dependency Analytics Report in editor groups

### PR DESCRIPTION
**Pull request by mathur07**
**SS#1**
Screenshot from 2020-10-05 12-11-17-edit

**SS#2**
image

### CODE REVIEW

**Comment by mathur07** [comment]
[test]

**Comment by arajkumar** [comment]
@mathur07 Could you please add a full window screenshot?

**Comment by mathur07** [comment]
@arajkumar added a full window screenshot ([SS#1](https://user-images.githubusercontent.com/23407383/95052367-6e82cd00-070c-11eb-9592-011a8052feee.png))

**Comment by arajkumar** [comment]
@mathur07 What does this icon signifies? Also only this icon seem to be in color, rest all are in monochrome.

**Comment by mathur07** [comment]
@arunkumars08, for now, its pie [icon](https://www.iconfinder.com/iconsets/6x16-free-application-icons) signifying a report.

**Comment by mathur07** [comment]
@arajkumar we will soon update it will a new RedHat icon

**Comment by arajkumar** [comment]
Why not https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/icon/openshift_logo.png for now?

**Review by arajkumar — APPROVED** [review]
lgtm

**Pull request merged**
