### PR TITLE
fix: Notification Button

### PR DESCRIPTION
**Pull request by dvandra**
fix: Notification Button (Show Dependency Analytics Report by clicking on the notification button.)

### CODE REVIEW

**Review by arajkumar — APPROVED** [review]
Litmus

**Comment by dvandra** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by arajkumar** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Pull request merged**
