### PR TITLE
chore: Version update to 0.2.0

### PR DESCRIPTION
**Pull request by mathur07**

### CODE REVIEW

**Review by arajkumar — APPROVED** [review]
lgtm

**Review by dvandra — APPROVED** [review]
LGTM

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by arajkumar** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by mathur07** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Comment by arajkumar** [comment]
[test]

**Comment by dvandra** [comment]
[test]

**Pull request merged**
