### PR TITLE
chore:  [Must be reverted] Update stage urls for user management testing on stage

### PR DESCRIPTION
**Pull request by mathur07**

### CODE REVIEW

**Review by dvandra — APPROVED** [review]
LGTM

**Comment by mathur07** [comment]
looking into the failed case.

**Review by arajkumar — APPROVED** [review]
Long term scalable solution would be using staging connect API.

**Comment by mathur07** [comment]
@arajkumar ya Arun that's what I was trying to archive but I could not find the correct THREE_SCALE_CONNECT_URL & THREE_SCALE_CONNECT_KEY for staging.

**Pull request merged**
