### PR TITLE
fix: Report generation fails with virtualenv enabled python

### LINKED ISSUE #398: Can't generate Dependency Analytics Report for requirements.txt
When I right-click `requirements.txt` in my Python project and select `Dependency Analytics Report`, an error message pops up:
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

My project uses a virtual environment generated using the Python standard library's `venv` package

## System Info

* OS: MacOS 10.15.5 (19F101)
* Extension Version: 0.1.0
* VSCode:
  * Version: 1.47.0
  * Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
  * Date: 2020-07-09T08:01:54.115Z
  * Electron: 7.3.2
  * Chrome: 78.0.3904.130
  * Node.js: 12.8.1
  * V8: 7.8.279.23-electron.0
  * OS: Darwin x64 19.5.0

### PR DESCRIPTION
**Pull request by mathur07**
Fixes #398

### CODE REVIEW

**Comment by mathur07** [comment]
Removed --user for vm support.

**Comment by mathur07** [comment]
These new space changes come in automatically due to auto indenting.

**Comment by mathur07** [comment]
Yes i did check it with Python plugin.

**Review by prashbnair — APPROVED** [review]

**Review by arajkumar — APPROVED** [review]
lgtm

**Pull request merged**
