### PR TITLE
feat: Golang Support for stack analyses

### PR DESCRIPTION
**Pull request by dvandra**
Added support for GO ecosystem:

https://issues.redhat.com/browse/APPAI-1462

This reverts #415.

### CODE REVIEW

**Review by dgpatelgit — APPROVED** [review]
Changes is a revert of previously done things. Lets put this in first place and separate PR for new top-up changes.

**Comment by arajkumar** [comment]
I would suggest to revert #415 through GH interface to maintain the context in the git history.

**Review by arajkumar — APPROVED** [review]
lgtm

**Review by mathur07 — APPROVED** [review]

**Review by mathur07 — APPROVED** [review]

**Review by arajkumar — APPROVED** [review]
lgtm

**Review by dgpatelgit — APPROVED** [review]

**Pull request merged**
